---
- name: Set up cluster-wide configuration.
  hosts: cluster
  gather_facts: false
  become: true

  handlers:
    - name: reboot-pi
      reboot:

  vars_files:
    - config.yml

  tasks: []


- name: Configure the control plane (node 1).
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks:
    # See: https://forums.raspberrypi.com/viewtopic.php?t=274486
    - name: Set up the Debian unstable repo.
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian unstable main contrib non-free
        state: present

    # See: https://ceph.com/en/news/blog/2022/install-ceph-in-a-raspberrypi-4-cluster/
    - name: Install cephadm (and other pacages).
      ansible.builtin.package:
        name:
          - podman
          - catatonit   # it crashes without this one
          - lvm2
          - cephadm
        state: present

    - name: Check if a ceph is bootstraped
      register: bootstraped
      stat: path=/etc/ceph/ceph.conf get_md5=no

    - name: Create the ceph cluster.
      shell: "cephadm bootstrap --mon-ip {{ ansible_host }}"  # inventory ex: pi001 ansible_host=192.168.1.101
      when: bootstraped.stat.exists == False

    - name: Retrieve the ceph pubkey.
      ansible.builtin.fetch:
        src: /etc/ceph/ceph.pub
        dest: files/ceph.pub
        flat: yes

    # Maybe we should merge this one with the L33
    - name: Ensure NFS dependencies are installed.
      ansible.builtin.package:
        name:
          - libcephfs2
          - nfs-ganesha
          - nfs-ganesha-ceph
        state: present

- name: Configure the nodes (nodes 2-6).
  hosts: nodes
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Ensure Ceph dependencies are installed.
      ansible.builtin.package:
        name:
          - podman
          - catatonit
          - lvm2
        state: present

    - name: Copy the ceph pubkey to each node.
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'files/ceph.pub') }}"
